# Configuración de plantillas de Issues para Psiconecta
# Evita que se creen Issues vacíos y fuerza el uso de los formularios institucionales.

blank_issues_enabled: false

contact_links:
  - name: 📧 Correo oficial
    url: mailto:royerwatson@gmail.com
    about: Si tienes una incidencia que requiere atención confidencial o profesional, escríbenos aquí.

